# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Install tcpdump and other necessary packages
RUN apt-get update && apt-get install -y tcpdump

# Copy the current directory contents into the container at /app
COPY process.py .

# Run process.py when the container launches
ENTRYPOINT ["python", "process.py"]
