version: '3.8'

services:
  styx-web:
    container_name: styx-web
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - styx-net
    restart: unless-stopped

networks:
  styx-net:
    external: true
