version: '3.8'

services:
  styx-web:
    container_name: styx-web
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../html:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - styx-net

networks:
  styx-net:
    external: true
