version: '3.8'

services:
  styx-dpi:
    build:
      context: ..
      dockerfile: Dockerfile.dpi
    environment:
      - DB_PATH=${DB_PATH:-data/styx-dpi.db}
      - INTERFACE=${INTERFACE:-wlan0}
      - LOG_PATH=${LOG_PATH:-/app/log/pihole.log}
    volumes:
      - ../data:/app/data
      - /srv/styx-pihole/var/log/pihole:/app/log
    network_mode: "host"
    container_name: styx-dpi

  styx-api:
    build:
      context: ..
      dockerfile: Dockerfile.api
    ports:
      - "${PORT:-8192}:${PORT:-8192}"
    environment:
      - DB_PATH=${DB_PATH:-data/styx-dpi.db}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8192}
    volumes:
      - ../data:/app/data
    container_name: styx-api
