version: '3.8'

services:
  styx-api:
    container_name: styx-api
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - DB_PATH=${DB_PATH}
      - HOST=${HOST}
      - PORT=${PORT}
    volumes:
      - /srv/styx-dpi/data:/app/data
    ports:
      - "${PORT}:${PORT}"
    networks:
      - styx-net
    restart: unless-stopped

networks:
  styx-net:
    external: true
