version: "3"

services:
  pihole:
    container_name: styx-pihole
    image: pihole/pihole:latest
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${WEBPASSWORD}
      PIHOLE_DNS_: ${PIHOLE_DNS}
      WEB_PORT: 8080
    volumes:
      - '${SERVICE_HOME}/etc/pihole:/etc/pihole'
      - '${SERVICE_HOME}/etc/dnsmasq.d:/etc/dnsmasq.d'
      - '${SERVICE_HOME}/var/log/pihole:/var/log/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:8080/tcp"
    networks:
      - styx-net

networks:
  styx-net:
    external: true
