version: '3.8'

services:
  styx-relay:
    container_name: styx-relay
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - UDP_PORT=${UDP_PORT:-8192}
    ports:
      - ${UDP_PORT:-8192}:${UDP_PORT:-8192}/udp
    networks:
      - styx-net
    restart: unless-stopped

networks:
  styx-net:
    external: true
