name: Generate ReDoc API Documentation

on:
  push:
    branches:
      - main  # Run this workflow when pushing to the main branch
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Generate ReDoc API Documentation
        run: |
          npx @redocly/cli build-docs https://jigsaw-studio.github.io/styx-os/openapi.json -o docs/api.html

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/api.html
          git commit -m "Update API documentation" || echo "No changes to commit"
          git push
